CREATE TABLE
    IF NOT EXISTS PROFILI (
        ID NUMERIC NOT NULL PRIMARY KEY,
        VARDS VARCHAR(50) NOT NULL,
        UZVARDS VARCHAR(50) NOT NULL,
        EPASTS VARCHAR(100),
        PAROLE VARCHAR(30) NOT NULL,
        DARBAVIETA VARCHAR(100),
        TIPS VARCHAR(30) NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS PASUTIJUMI (
        ID NUMERIC NOT NULL PRIMARY KEY,
        PRECES TEXT (1000) NOT NULL,
        NOLIKTAVAS_NOSAUKUMS TEXT (100) NOT NULL,
        RAZOTNES_NOSAUKUMS TEXT (100) NOT NULL,
        STATUSS TEXT (15) NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS RAZOTAJA_PRECES (
        ID NUMERIC NOT NULL PRIMARY KEY,
        NOSAUKUMS TEXT (100) NOT NULL,
        DAUDZUMS NUMERIC NOT NULL,
        KATEGORIJA TEXT (50),
        CENA NUMBER (6, 2) NOT NULL,
        RAZOTAJS TEXT (100) NOT NULL,
        PRECES_APRAKSTS TEXT (1000)
    );

CREATE TABLE
    IF NOT EXISTS NOLIKTAVAS_PRECES (
        ID INTEGER NOT NULL PRIMARY KEY,
        NOSAUKUMS TEXT (100) NOT NULL,
        DAUDZUMS NUMERIC NOT NULL,
        KATEGORIJA TEXT (50),
        CENA NUMBER (6, 2) NOT NULL,
        RAZOTAJS TEXT (100) NOT NULL,
        PRECES_APRAKSTS TEXT (1000)
    );

CREATE TABLE
    IF NOT EXISTS AUDITS (
        ID NUMERIC NOT NULL PRIMARY KEY,
        DARBIBA TEXT (1000) NOT NULL,
        LIETOTAJA_ID NUMERIC NOT NULL,
        LAIKS TEXT (50) NOT NULL,
        CONSTRAINT AUDITS_PROFILI_FK FOREIGN KEY (LIETOTAJA_ID) REFERENCES PROFILI (ID)
    );

INSERT INTO
    PROFILI (ID, VARDS, UZVARDS, PAROLE, TIPS)
VALUES
    (1, 'Jānis', 'Programmētājs', 'P@55w0rd', 'Admin');